### ISSUE TITLE
Social Media Marketing help - API Testing Workshop (Pricilla Bilavendran)

### ISSUE THREAD

**Issue by Pricilla09** [Kcorb95/Postman-Supernova-Program-Resources#4]
# Contribution Proposal

## Contribution Type
- [x] Event Speaking
- [ ] Event Hosting
- [ ] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [ ] Virtual
- [x] In-Person
- [ ] Hybrid

### Contribution Name
API Testing Workshop

### Contribution Date
09/06/2023

### Link to Contribution (optional)
Link to your contribution, if applicable

### Projected Attendance (optional)
100+

# Details
It's a detailed API Testing Workshop for 4 hrs.
To provide an overview of APIs and API Testing
To start the hands-on workshop using Postman and how to use it for API Testing
Website link: https://softecasia.org/

Dates: 5th and 6th September, Venue: Double Tree by Hilton, KL, Malaysia.

**Comment by Kcorb95** [comment]
Hey @Pricilla09 ! Thanks for the submission. I've made a copy of it in the official repo as this one is not meant to be used unfortunately :) Let me know if you want any swag sent your way as well!
https://github.com/postman-open-technologies/Postman-Supernova-Program/issues/16
